kind: Service
apiVersion: v1
metadata:
  name: outside
  namespace: dev
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32400
    nodePort: 32400
  type: NodePort
