apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kafka-broker
  resources:
    requests:
      storage: 130Gi
